# -*- coding: utf-8 -*-
"""DataScienceCapstone.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Z7IVbo9lj46wltDqAUm2-aBDT637oL0

This notebook will be used for Capstone Project.
"""

import pandas as pd
import numpy as np

print("Hello Capstone Project Course!")

